# Static configuration for Traefik
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.traefik.me"
            # sans:
            #   - "traefik.me"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: info@leonscherer.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
# Optional: Enable access logs
# accessLog: {}

# Optional: Enable Traefik logs
# log:
#   level: INFO
